resolver: lts-8.11
packages:
- .
- ../api
- location:
    git: https://github.com/liqula/react-hs
    commit: 0795a78b05ace05502994bb082979bfd7a35ea0c
  extra-dep: true
  subdirs:
  - react-hs
extra-deps:
- aeson-1.1.1.0
- datetime-0.3.1
- ghcjs-base-stub-0.1.0.2
